use std::fs;
use std::io::Write;
use std::path::PathBuf;

// The chip table is shared with the application example so that both binaries
// resolve the chip feature to the same partition map.
include!("../chips.rs");

/// The region this binary is placed in.
const REGION: &str = "BOOTLOADER";

fn main() {
    let chip = selected("examples/bootloader");
    check_target(chip);

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // `link.x` (provided by qingke-rt) does `INCLUDE memory.x`, so we generate a
    // `memory.x` that pulls in the partition map for the selected chip and
    // aliases this binary's region to `FLASH`.
    let memory_x = format!(
        "/* generated by build.rs, do not edit */\n\
         INCLUDE {map}\n\
         \n\
         REGION_ALIAS(\"FLASH\", {REGION})\n\
         REGION_ALIAS(\"REGION_TEXT\", FLASH)\n\
         REGION_ALIAS(\"REGION_RODATA\", FLASH)\n\
         REGION_ALIAS(\"REGION_DATA\", RAM)\n\
         REGION_ALIAS(\"REGION_BSS\", RAM)\n\
         REGION_ALIAS(\"REGION_HEAP\", RAM)\n\
         REGION_ALIAS(\"REGION_STACK\", RAM)\n",
        map = chip.map,
    );
    write_if_changed(&out_dir.join("memory.x"), memory_x.as_bytes());

    // Small module for `src/main.rs`: the banner has to say which part this is.
    let chip_rs = format!(
        "/// The selected part, as a lower case part number (a cargo feature name).\n\
         pub const CHIP: &str = \"{part}\";\n\
         /// The selected part, upper case, for console messages.\n\
         pub const CHIP_NAME: &str = \"{name}\";\n\
         /// The partition map this binary was linked against.\n\
         pub const PARTITION_MAP: &str = \"{map}\";\n",
        part = chip.part,
        name = chip.part.to_uppercase(),
        map = chip.map,
    );
    write_if_changed(&out_dir.join("chip.rs"), chip_rs.as_bytes());

    // Our generated `memory.x` has to be found before anything else, the
    // partition map directory is needed for its `INCLUDE`.
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!(
        "cargo:rustc-link-search=native={}",
        manifest.join("../../partition-map").display()
    );
    println!("cargo:rustc-link-arg-bins=-Tlink.x");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../chips.rs");
    println!(
        "cargo:rerun-if-changed={}",
        manifest
            .join("../../partition-map")
            .join(chip.map)
            .display()
    );
}

/// Writes `path` only when the contents differ, so that touching a generated
/// file does not force a relink.
fn write_if_changed(path: &PathBuf, contents: &[u8]) {
    if fs::read(path).is_ok_and(|existing| existing == contents) {
        return;
    }
    let mut file =
        fs::File::create(path).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    file.write_all(contents)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
}
