use std::fs;
use std::io::Write;
use std::path::PathBuf;

// The chip table is shared with the application example so that both binaries
// resolve the chip feature to the same partition map.
include!("../chips.rs");

/// The region this binary is placed in.
const REGION: &str = "BOOTLOADER";

/// The update transport selected by the `transport-*` features.
#[derive(Clone, Copy, PartialEq)]
enum Transport {
    Uart,
    Usb,
    Can,
}

fn main() {
    let chip = selected("examples/bootloader");
    check_target(chip);

    let transport = selected_transport("examples/bootloader");

    // A USB bootloader needs a bigger bootloader partition than a serial one,
    // so parts that support it are linked against a second map. The CAN
    // transport keeps the serial geometry but needs the CAN controller, so it
    // gets its own map as well.
    let map = match transport {
        Transport::Uart => chip.map,
        Transport::Usb => {
            if chip.map_usb.is_empty() {
                panic!(
                    "examples/bootloader: {part} does not support the `transport-usb` feature ({}). \
                     Parts without a `ch32-hal` USB driver, and the 64 KiB CH32V203 parts, are \
                     serial only; build with `--features {part}` instead.",
                    if chip.usb.is_empty() {
                        "it has no USB driver in ch32-hal"
                    } else {
                        "its flash is too small for a USB bootloader"
                    },
                    part = chip.part,
                );
            }
            chip.map_usb
        }
        Transport::Can => {
            if chip.map_can.is_empty() {
                panic!(
                    "examples/bootloader: {part} does not support the `transport-can` feature \
                     ({}); build with `--features {part}` for the serial bootloader.",
                    if chip.can {
                        "its flash is too small for a CAN bootloader"
                    } else {
                        "it has no CAN controller"
                    },
                    part = chip.part,
                );
            }
            chip.map_can
        }
    };

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Which USB controller the source has to drive. Declared unconditionally so
    // that `cfg(usb_*)` never trips `unexpected_cfgs` in a serial build.
    for cfg in ["usb_usbd", "usb_otg_fs", "usb_usbhs"] {
        println!("cargo::rustc-check-cfg=cfg({cfg})");
    }
    if transport == Transport::Usb {
        println!("cargo::rustc-cfg=usb_{}", chip.usb);
    }

    // `link.x` (provided by qingke-rt) does `INCLUDE memory.x`, so we generate a
    // `memory.x` that pulls in the partition map for the selected chip and
    // aliases this binary's region to `FLASH`.
    let memory_x = format!(
        "/* generated by build.rs, do not edit */\n\
         INCLUDE {map}\n\
         \n\
         REGION_ALIAS(\"FLASH\", {REGION})\n\
         REGION_ALIAS(\"REGION_TEXT\", FLASH)\n\
         REGION_ALIAS(\"REGION_RODATA\", FLASH)\n\
         REGION_ALIAS(\"REGION_DATA\", RAM)\n\
         REGION_ALIAS(\"REGION_BSS\", RAM)\n\
         REGION_ALIAS(\"REGION_HEAP\", RAM)\n\
         REGION_ALIAS(\"REGION_STACK\", RAM)\n",
        map = map,
    );
    write_if_changed(&out_dir.join("memory.x"), memory_x.as_bytes());

    // Small module for `src/main.rs`: the banner has to say which part this is.
    let chip_rs = format!(
        "/// The selected part, as a lower case part number (a cargo feature name).\n\
         pub const CHIP: &str = \"{part}\";\n\
         /// The selected part, upper case, for console messages.\n\
         pub const CHIP_NAME: &str = \"{name}\";\n\
         /// The partition map this binary was linked against.\n\
         pub const PARTITION_MAP: &str = \"{map}\";\n",
        part = chip.part,
        name = chip.part.to_uppercase(),
        map = map,
    );
    write_if_changed(&out_dir.join("chip.rs"), chip_rs.as_bytes());

    // Our generated `memory.x` has to be found before anything else, the
    // partition map directory is needed for its `INCLUDE`.
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!(
        "cargo:rustc-link-search=native={}",
        manifest.join("../../partition-map").display()
    );
    println!("cargo:rustc-link-arg-bins=-Tlink.x");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../chips.rs");
    println!(
        "cargo:rerun-if-changed={}",
        manifest.join("../../partition-map").join(map).display()
    );
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_TRANSPORT_UART");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_TRANSPORT_USB");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_TRANSPORT_CAN");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_CAN_PB8_PB9");
}

/// The one `transport-*` feature that is enabled.
///
/// All three transports could coexist in principle (a board with a console, a
/// USB socket and a CAN transceiver), but they do not fit in the bootloader
/// partition together, and a build that silently picks one of several enabled
/// transports is a bad way to find that out.
fn selected_transport(example: &str) -> Transport {
    let uart = std::env::var("CARGO_FEATURE_TRANSPORT_UART").is_ok_and(|v| v == "1");
    let usb = std::env::var("CARGO_FEATURE_TRANSPORT_USB").is_ok_and(|v| v == "1");
    let can = std::env::var("CARGO_FEATURE_TRANSPORT_CAN").is_ok_and(|v| v == "1");

    // The pin remap option only means something to the CAN transport; catching
    // it here gives a better message than silently building PA11/PA12 CAN.
    let pb8_pb9 = std::env::var("CARGO_FEATURE_CAN_PB8_PB9").is_ok_and(|v| v == "1");
    if pb8_pb9 && !can {
        panic!(
            "{example}: the `can-pb8-pb9` feature only applies to `transport-can`; it is enabled \
             without it."
        );
    }

    match (uart, usb, can) {
        (true, false, false) => Transport::Uart,
        (false, true, false) => Transport::Usb,
        (false, false, true) => Transport::Can,
        (false, false, false) => panic!(
            "{example}: no transport feature enabled. Enable `transport-uart`, `transport-usb` \
             or `transport-can`; the package enables `transport-uart` by default."
        ),
        _ => panic!(
            "{example}: more than one transport feature enabled; enable exactly one of \
             `transport-uart`, `transport-usb` and `transport-can`."
        ),
    }
}

/// Writes `path` only when the contents differ, so that touching a generated
/// file does not force a relink.
fn write_if_changed(path: &PathBuf, contents: &[u8]) {
    if fs::read(path).is_ok_and(|existing| existing == contents) {
        return;
    }
    let mut file =
        fs::File::create(path).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    file.write_all(contents)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
}
