use std::fs;
use std::io::Write;
use std::path::PathBuf;

// The chip table is shared with the bootloader example so that both binaries
// resolve the chip feature to the same partition map.
include!("../chips.rs");

/// The region this binary is placed in.
const REGION: &str = "ACTIVE";

fn main() {
    let chip = selected("examples/application");
    check_target(chip);

    // An application with the runtime DFU interface must be linked against the
    // same map as the USB bootloader it talks to, which is the `-usb` map of
    // the part.
    let usb_dfu = std::env::var("CARGO_FEATURE_USB_DFU").is_ok_and(|v| v == "1");
    let map = if usb_dfu {
        if chip.map_usb.is_empty() {
            panic!(
                "examples/application: {part} does not support the `usb-dfu` feature ({}). Build \
                 without it to get the plain serial application.",
                if chip.usb.is_empty() {
                    "it has no USB driver in ch32-hal"
                } else {
                    "its flash is too small for a USB bootloader"
                },
                part = chip.part,
            );
        }
        chip.map_usb
    } else {
        chip.map
    };

    // Which USB controller the `usb-dfu` build has to drive. Declared
    // unconditionally so that `cfg(usb_*)` never trips `unexpected_cfgs` in a
    // build without the feature.
    for cfg in ["usb_usbd", "usb_otg_fs", "usb_usbhs"] {
        println!("cargo::rustc-check-cfg=cfg({cfg})");
    }
    if usb_dfu {
        println!("cargo::rustc-cfg=usb_{}", chip.usb);
    }

    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // `link.x` (provided by qingke-rt) does `INCLUDE memory.x`, so we generate a
    // `memory.x` that pulls in the partition map for the selected chip and
    // aliases this binary's region to `FLASH`.
    let memory_x = format!(
        "/* generated by build.rs, do not edit */\n\
         INCLUDE {map}\n\
         \n\
         REGION_ALIAS(\"FLASH\", {REGION})\n\
         REGION_ALIAS(\"REGION_TEXT\", FLASH)\n\
         REGION_ALIAS(\"REGION_RODATA\", FLASH)\n\
         REGION_ALIAS(\"REGION_DATA\", RAM)\n\
         REGION_ALIAS(\"REGION_BSS\", RAM)\n\
         REGION_ALIAS(\"REGION_HEAP\", RAM)\n\
         REGION_ALIAS(\"REGION_STACK\", RAM)\n",
        map = map,
    );
    write_if_changed(&out_dir.join("memory.x"), memory_x.as_bytes());

    // Small module for `src/main.rs`: the banner has to say which part this is.
    let chip_rs = format!(
        "/// The selected part, as a lower case part number (a cargo feature name).\n\
         pub const CHIP: &str = \"{part}\";\n\
         /// The selected part, upper case, for console messages.\n\
         pub const CHIP_NAME: &str = \"{name}\";\n\
         /// The partition map this binary was linked against.\n\
         pub const PARTITION_MAP: &str = \"{map}\";\n",
        part = chip.part,
        name = chip.part.to_uppercase(),
        map = map,
    );
    write_if_changed(&out_dir.join("chip.rs"), chip_rs.as_bytes());

    // Our generated `memory.x` has to be found before anything else, the
    // partition map directory is needed for its `INCLUDE`.
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!(
        "cargo:rustc-link-search=native={}",
        manifest.join("../../partition-map").display()
    );
    println!("cargo:rustc-link-arg-bins=-Tlink.x");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../chips.rs");
    println!(
        "cargo:rerun-if-changed={}",
        manifest.join("../../partition-map").join(map).display()
    );
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_USB_DFU");
}

/// Writes `path` only when the contents differ, so that touching a generated
/// file does not force a relink.
fn write_if_changed(path: &PathBuf, contents: &[u8]) {
    if fs::read(path).is_ok_and(|existing| existing == contents) {
        return;
    }
    let mut file =
        fs::File::create(path).unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    file.write_all(contents)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
}
